---

- name: Configure privileged security context
  shell: |
    oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:px-account
    oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:portworx-pvc-controller-account
    oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:px-lh-account
    oc adm policy add-scc-to-user anyuid system:serviceaccount:kube-system:px-lh-account
    oc adm policy add-scc-to-user anyuid system:serviceaccount:default:default 

- name: Create secret for registry credentials
  shell: "oc create secret docker-registry {{ registrySecret }} \
  --docker-server={{ registryURL}} \
  --docker-username={{ registryUser }} \
  --docker-password={{ registryPassword }} \
  -n kube-system"

- name: Ensure kvdb-secrets directory exists
  file: path=/tmp/kvdb-secrets state=directory

- name: Copy kvdb certs to openshift master
  template: src=kvdb-ca.crt.j2 dest=/tmp/kvdb-secrets/kvdb-ca.crt

- name: Create secret for ETCD certificate
  shell: "oc -n kube-system create secret generic px-kvdb-auth --from-file=/tmp/kvdb-secrets/"

- name: Copy px-install.yaml to openshift master
  template: src=px-install-2.3.yaml.j2 dest=~/px-install-2.3.yaml

- name: Apply px-install.yaml on master
  shell: "oc apply -f ~/px-install-2.3.yaml"

- name: Wait for Portworx to become ready
  shell: "oc wait --namespace=kube-system --for=condition=Ready pods --selector name=portworx --timeout=120s"